from ymdantic.models.albums import Album, ShortAlbum
from ymdantic.models.artists import Artist, ArtistData, ShortArtist
from ymdantic.models.landing import (
    Chart,
    ChartBlock,
    EditorialResponse,
    InStyle,
    InStyleResponse,
    LandingAlbum,
    LandingAlbumItem,
    LandingAlbumItemData,
    LandingArtist,
    LandingArtistItem,
    LandingArtistItemData,
    LandingCustomWave,
    LandingLikedPlaylistItem,
    LandingLikedPlaylistItemData,
    LandingOpenPlaylist,
    LandingPersonalPlaylistItem,
    LandingPersonalPlaylistItemData,
    LandingPlaylist,
    LandingPlaylistItem,
    LandingPlaylistItemData,
    LandingPromotion,
    LandingPromotionResponse,
    LandingSpecial,
    LandingWaves,
    LandingWavesResponse,
    NewRelease,
    NewReleasesResponse,
    SkeletonResponse,
)
from ymdantic.models.landing3 import NewReleasesBlock, OldChartBlock
from ymdantic.models.playlists import Playlist
from ymdantic.models.response import Response
from ymdantic.models.s3 import S3FileUrl
from ymdantic.models.search import SearchInstantMixedResponse, SearchParams
from ymdantic.models.tracks import (
    DownloadInfo,
    DownloadInfoDirect,
    FileInfo,
    FileInfoParams,
    FileInfoWrapped,
    Podcast,
    Track,
    TrackType,
    UnavailablePodcast,
    UnavailableTrack,
)

# Ребилд моделей с учётом новых изменений. (TrackType)
ShortAlbum.model_rebuild()
Album.model_rebuild()
ArtistData.model_rebuild()

__all__ = (
    "Album",
    "Artist",
    "ArtistData",
    "Chart",
    "ChartBlock",
    "DownloadInfo",
    "DownloadInfoDirect",
    "EditorialResponse",
    "FileInfo",
    "FileInfoParams",
    "FileInfoWrapped",
    "InStyle",
    "InStyleResponse",
    "LandingAlbum",
    "LandingAlbumItem",
    "LandingAlbumItemData",
    "LandingArtist",
    "LandingArtistItem",
    "LandingArtistItemData",
    "LandingCustomWave",
    "LandingLikedPlaylistItem",
    "LandingLikedPlaylistItemData",
    "LandingOpenPlaylist",
    "LandingPersonalPlaylistItem",
    "LandingPersonalPlaylistItemData",
    "LandingPlaylist",
    "LandingPlaylistItem",
    "LandingPlaylistItemData",
    "LandingPromotion",
    "LandingPromotionResponse",
    "LandingSpecial",
    "LandingWaves",
    "LandingWavesResponse",
    "NewRelease",
    "NewReleasesBlock",
    "NewReleasesResponse",
    "OldChartBlock",
    "Playlist",
    "Podcast",
    "Response",
    "S3FileUrl",
    "SearchInstantMixedResponse",
    "SearchParams",
    "ShortAlbum",
    "ShortArtist",
    "SkeletonResponse",
    "Track",
    "TrackType",
    "UnavailablePodcast",
    "UnavailableTrack",
)
